import React from "react";
import "./style.css";
import JsonDiff from "./jsonDiff/JsonDiff";
export default function App() {
  const data = [
    {
      "apk_source": "google_play_link",
      "app_assets": [],
      "app_assets_source": "google_play_store",
      "app_category": {
        "en": "Action"
      },
      "app_description": {},
      "app_developer_info": {
        "developer_name": "bluestack",
        "official_email_id": "bluestacks.com",
        "official_website": "nowgg.com",
        "privacy_policy": "policy",
        "terms_of_services": "services"
      },
      "app_id": "61d2b85d2b8108a55d00b767",
      "app_pkg_name": "game.action",
      "app_playstore_url": "google.play.com",
      "app_prod_url": "",
      "app_published_regions": {
        "APAC": [
          "WF",
          "WS",
          "G",
          "PW",
          "PF",
          "PG",
          "PK",
          "PN",
          "MO",
          "MN",
          "MH",
          "MV",
          "MP",
          "FJ",
          "FM",
          "CK",
          "CN",
          "CC",
          "CX",
          "SY",
          "SB",
          "LK",
          "IO",
          "BD",
          "BT",
          "HK",
          "HM",
          "UZ",
          "UM",
          "V",
          "NC",
          "NF",
          "NZ",
          "NP",
          "NR",
          "N",
          "KG",
          "KI",
          "KP",
          "KZ",
          "TV",
          "TW",
          "TO",
          "TM",
          "TJ",
          "TK",
          "TF",
          "AF",
          "AQ",
          "AS",
          "A",
          "AZ"
        ],
        "EasternEurope": [
          "JE",
          "GR",
          "GG",
          "GE",
          "GL",
          "GI",
          "PT",
          "PL",
          "ME",
          "MD",
          "MC",
          "MK",
          "MT",
          "FO",
          "CZ",
          "CY",
          "SK",
          "SJ",
          "SI",
          "SM",
          "LI",
          "LV",
          "LT",
          "L",
          "VA",
          "IS",
          "IT",
          "IM",
          "IL",
          "BE",
          "BG",
          "BA",
          "BY",
          "RU",
          "RS",
          "RO",
          "HR",
          "H",
          "EE",
          "ES",
          "UA",
          "TR",
          "AD",
          "AM",
          "AL"
        ],
        "India": [
          "IN"
        ],
        "Japan": [
          "JP"
        ],
        "MEA": [
          "JO",
          "GW",
          "GQ",
          "GA",
          "GN",
          "GM",
          "GH",
          "PS",
          "ZM",
          "ZA",
          "ZW",
          "MG",
          "MA",
          "ML",
          "M",
          "MW",
          "MR",
          "MZ",
          "CI",
          "CM",
          "CG",
          "CF",
          "CD",
          "CV",
          "SZ",
          "SS",
          "ST",
          "SH",
          "SO",
          "SN",
          "SL",
          "SC",
          "SA",
          "SD",
          "YE",
          "YT",
          "LB",
          "LR",
          "LS",
          "LY",
          "IQ",
          "IR",
          "BF",
          "BH",
          "BI",
          "BJ",
          "BW",
          "RW",
          "RE",
          "OM",
          "EH",
          "EG",
          "ET",
          "ER",
          "UG",
          "NA",
          "NE",
          "NG",
          "KE",
          "KM",
          "KW",
          "DJ",
          "DZ",
          "TZ",
          "TN",
          "TG",
          "TD",
          "AE",
          "AO",
          "QA"
        ],
        "NorthAmerica": [
          "PM",
          "MF",
          "CA",
          "SX",
          "BL",
          "US"
        ],
        "SouthAmerica": [
          "JM",
          "GT",
          "GS",
          "GP",
          "GY",
          "GF",
          "GD",
          "PR",
          "PY",
          "PA",
          "PE",
          "MQ",
          "MS",
          "MX",
          "FK",
          "CO",
          "CL",
          "CR",
          "CW",
          "C",
          "SR",
          "SV",
          "LC",
          "VC",
          "VE",
          "VG",
          "VI",
          "BB",
          "BM",
          "BO",
          "BV",
          "BQ",
          "BR",
          "BS",
          "BZ",
          "HT",
          "HN",
          "EC",
          "UY",
          "NI",
          "KN",
          "KY",
          "DO",
          "DM",
          "TT",
          "TC",
          "AG",
          "AI",
          "AR",
          "AW"
        ],
        "SouthEastAsia": [
          "PH",
          "MM",
          "MY",
          "SG",
          "LA",
          "VN",
          "ID",
          "BN",
          "KH",
          "TL",
          "TH"
        ],
        "SouthKorea": [
          "KR"
        ],
        "WesternEurope": [
          "GB",
          "FR",
          "FI",
          "CH",
          "SE",
          "IE",
          "NL",
          "NO",
          "DK",
          "DE",
          "AT",
          "AX"
        ]
      },
      "app_sub_category": {},
      "app_testing_url": "",
      "app_title": {
        "en": "action game 3rd version"
      },
      "app_version": "",
      "app_version_code": null,
      "comments": [],
      "created_at": 1641530621521,
      "created_by": "nitin.jayant@bluestacks.com",
      "custom_domain_url": "custom",
      "dev_apk_link": "",
      "id": "61d7c4fd8deb7a633ad85216",
      "last_updated_by": "nitin.jayant@bluestacks.com",
      "live_apk_url": "",
      "modified_at": 1641531123181,
      "submission_state": "submitted",
      "submission_type": "metadata_change",
      "uploaded_apk_url": ""
    },
    {
      "apk_source": "google_play_link",
      "app_assets": [],
      "app_assets_source": "google_play_store",
      "app_category": {
        "en": "Action"
      },
      "app_description": {},
      "app_developer_info": {
        "developer_name": "bluestack",
        "official_email_id": "bluestacks.com",
        "official_website": "nowgg.com",
        "privacy_policy": "policy",
        "terms_of_services": "services"
      },
      "app_id": "61d2b85d2b8108a55d00b767",
      "app_pkg_name": "game.action",
      "app_playstore_url": "google.play.com",
      "app_prod_url": "pub",
      "app_published_regions": {
        "APAC": [
          "WF",
          "WS",
          "G",
          "PW",
          "PF",
          "PG",
          "PK",
          "PN",
          "MO",
          "MN",
          "MH",
          "MV",
          "MP",
          "FJ",
          "FM",
          "CK",
          "CN",
          "CC",
          "CX",
          "SY",
          "SB",
          "LK",
          "IO",
          "BD",
          "BT",
          "HK",
          "HM",
          "UZ",
          "UM",
          "V",
          "NC",
          "NF",
          "NZ",
          "NP",
          "NR",
          "N",
          "KG",
          "KI",
          "KP",
          "KZ",
          "TV",
          "TW",
          "TO",
          "TM",
          "TJ",
          "TK",
          "TF",
          "AF",
          "AQ",
          "AS",
          "A",
          "AZ"
        ],
        "EasternEurope": [
          "JE",
          "GR",
          "GG",
          "GE",
          "GL",
          "GI",
          "PT",
          "PL",
          "ME",
          "MD",
          "MC",
          "MK",
          "MT",
          "FO",
          "CZ",
          "CY",
          "SK",
          "SJ",
          "SI",
          "SM",
          "LI",
          "LV",
          "LT",
          "L",
          "VA",
          "IS",
          "IT",
          "IM",
          "IL",
          "BE",
          "BG",
          "BA",
          "BY",
          "RU",
          "RS",
          "RO",
          "HR",
          "H",
          "EE",
          "ES",
          "UA",
          "TR",
          "AD",
          "AM",
          "AL"
        ],
        "India": [
          "IN"
        ],
        "Japan": [
          "JP"
        ],
        "MEA": [
          "JO",
          "GW",
          "GQ",
          "GA",
          "GN",
          "GM",
          "GH",
          "PS",
          "ZM",
          "ZA",
          "ZW",
          "MG",
          "MA",
          "ML",
          "M",
          "MW",
          "MR",
          "MZ",
          "CI",
          "CM",
          "CG",
          "CF",
          "CD",
          "CV",
          "SZ",
          "SS",
          "ST",
          "SH",
          "SO",
          "SN",
          "SL",
          "SC",
          "SA",
          "SD",
          "YE",
          "YT",
          "LB",
          "LR",
          "LS",
          "LY",
          "IQ",
          "IR",
          "BF",
          "BH",
          "BI",
          "BJ",
          "BW",
          "RW",
          "RE",
          "OM",
          "EH",
          "EG",
          "ET",
          "ER",
          "UG",
          "NA",
          "NE",
          "NG",
          "KE",
          "KM",
          "KW",
          "DJ",
          "DZ",
          "TZ",
          "TN",
          "TG",
          "TD",
          "AE",
          "AO",
          "QA"
        ],
        "NorthAmerica": [
          "PM",
          "MF",
          "CA",
          "SX",
          "BL",
          "US"
        ],
        "SouthAmerica": [
          "JM",
          "GT",
          "GS",
          "GP",
          "GY",
          "GF",
          "GD",
          "PR",
          "PY",
          "PA",
          "PE",
          "MQ",
          "MS",
          "MX",
          "FK",
          "CO",
          "CL",
          "CR",
          "CW",
          "C",
          "SR",
          "SV",
          "LC",
          "VC",
          "VE",
          "VG",
          "VI",
          "BB",
          "BM",
          "BO",
          "BV",
          "BQ",
          "BR",
          "BS",
          "BZ",
          "HT",
          "HN",
          "EC",
          "UY",
          "NI",
          "KN",
          "KY",
          "DO",
          "DM",
          "TT",
          "TC",
          "AG",
          "AI",
          "AR",
          "AW"
        ],
        "SouthEastAsia": [
          "PH",
          "MM",
          "MY",
          "SG",
          "LA",
          "VN",
          "ID",
          "BN",
          "KH",
          "TL",
          "TH"
        ],
        "SouthKorea": [
          "KR"
        ],
        "WesternEurope": [
          "GB",
          "FR",
          "FI",
          "CH",
          "SE",
          "IE",
          "NL",
          "NO",
          "DK",
          "DE",
          "AT",
          "AX"
        ]
      },
      "app_sub_category": {},
      "app_testing_url": "tesr",
      "app_title": {
        "en": "action game 2nd version"
      },
      "app_version": "",
      "app_version_code": null,
      "comments": [
        {
          "comment_text": "pub",
          "commented_at": {
            "$date": 1641530588612
          },
          "commented_by": "nitin.jayant@bluestacks.com",
          "from_state": "ready_for_publishing",
          "to_state": "published"
        },
        {
          "comment_text": "ready",
          "commented_at": {
            "$date": 1641530470502
          },
          "commented_by": "nitin.jayant@bluestacks.com",
          "from_state": "under_testing",
          "to_state": "ready_for_publishing"
        },
        {
          "comment_text": "test",
          "commented_at": {
            "$date": 1641530460890
          },
          "commented_by": "nitin.jayant@bluestacks.com",
          "from_state": "submitted",
          "to_state": "under_testing"
        }
      ],
      "created_at": 1641529830344,
      "created_by": "nitin.jayant@bluestacks.com",
      "custom_domain_url": "custom",
      "dev_apk_link": "",
      "id": "61d7c1e68deb7a633ad85215",
      "last_updated_by": "nitin.jayant@bluestacks.com",
      "live_apk_url": "",
      "modified_at": 1641530588612,
      "submission_state": "published",
      "submission_type": "metadata_change",
      "uploaded_apk_url": ""
    },
    {
      "apk_source": "google_play_link",
      "app_assets": [],
      "app_assets_source": "google_play_store",
      "app_category": {
        "en": "Action"
      },
      "app_description": {},
      "app_developer_info": {
        "developer_name": "bluestack",
        "official_email_id": "bluestacks.com",
        "official_website": "nowgg.com",
        "privacy_policy": "policy",
        "terms_of_services": "services"
      },
      "app_id": "61d2b85d2b8108a55d00b767",
      "app_pkg_name": "game.action",
      "app_playstore_url": "google.play.com",
      "app_prod_url": "publish",
      "app_published_regions": {
        "APAC": [
          "WF",
          "WS",
          "G",
          "PW",
          "PF",
          "PG",
          "PK",
          "PN",
          "MO",
          "MN",
          "MH",
          "MV",
          "MP",
          "FJ",
          "FM",
          "CK",
          "CN",
          "CC",
          "CX",
          "SY",
          "SB",
          "LK",
          "IO",
          "BD",
          "BT",
          "HK",
          "HM",
          "UZ",
          "UM",
          "V",
          "NC",
          "NF",
          "NZ",
          "NP",
          "NR",
          "N",
          "KG",
          "KI",
          "KP",
          "KZ",
          "TV",
          "TW",
          "TO",
          "TM",
          "TJ",
          "TK",
          "TF",
          "AF",
          "AQ",
          "AS",
          "A",
          "AZ"
        ],
        "EasternEurope": [
          "JE",
          "GR",
          "GG",
          "GE",
          "GL",
          "GI",
          "PT",
          "PL",
          "ME",
          "MD",
          "MC",
          "MK",
          "MT",
          "FO",
          "CZ",
          "CY",
          "SK",
          "SJ",
          "SI",
          "SM",
          "LI",
          "LV",
          "LT",
          "L",
          "VA",
          "IS",
          "IT",
          "IM",
          "IL",
          "BE",
          "BG",
          "BA",
          "BY",
          "RU",
          "RS",
          "RO",
          "HR",
          "H",
          "EE",
          "ES",
          "UA",
          "TR",
          "AD",
          "AM",
          "AL"
        ],
        "India": [
          "IN"
        ],
        "Japan": [
          "JP"
        ],
        "MEA": [
          "JO",
          "GW",
          "GQ",
          "GA",
          "GN",
          "GM",
          "GH",
          "PS",
          "ZM",
          "ZA",
          "ZW",
          "MG",
          "MA",
          "ML",
          "M",
          "MW",
          "MR",
          "MZ",
          "CI",
          "CM",
          "CG",
          "CF",
          "CD",
          "CV",
          "SZ",
          "SS",
          "ST",
          "SH",
          "SO",
          "SN",
          "SL",
          "SC",
          "SA",
          "SD",
          "YE",
          "YT",
          "LB",
          "LR",
          "LS",
          "LY",
          "IQ",
          "IR",
          "BF",
          "BH",
          "BI",
          "BJ",
          "BW",
          "RW",
          "RE",
          "OM",
          "EH",
          "EG",
          "ET",
          "ER",
          "UG",
          "NA",
          "NE",
          "NG",
          "KE",
          "KM",
          "KW",
          "DJ",
          "DZ",
          "TZ",
          "TN",
          "TG",
          "TD",
          "AE",
          "AO",
          "QA"
        ],
        "NorthAmerica": [
          "PM",
          "MF",
          "CA",
          "SX",
          "BL",
          "US"
        ],
        "SouthAmerica": [
          "JM",
          "GT",
          "GS",
          "GP",
          "GY",
          "GF",
          "GD",
          "PR",
          "PY",
          "PA",
          "PE",
          "MQ",
          "MS",
          "MX",
          "FK",
          "CO",
          "CL",
          "CR",
          "CW",
          "C",
          "SR",
          "SV",
          "LC",
          "VC",
          "VE",
          "VG",
          "VI",
          "BB",
          "BM",
          "BO",
          "BV",
          "BQ",
          "BR",
          "BS",
          "BZ",
          "HT",
          "HN",
          "EC",
          "UY",
          "NI",
          "KN",
          "KY",
          "DO",
          "DM",
          "TT",
          "TC",
          "AG",
          "AI",
          "AR",
          "AW"
        ],
        "SouthEastAsia": [
          "PH",
          "MM",
          "MY",
          "SG",
          "LA",
          "VN",
          "ID",
          "BN",
          "KH",
          "TL",
          "TH"
        ],
        "SouthKorea": [
          "KR"
        ],
        "WesternEurope": [
          "GB",
          "FR",
          "FI",
          "CH",
          "SE",
          "IE",
          "NL",
          "NO",
          "DK",
          "DE",
          "AT",
          "AX"
        ]
      },
      "app_sub_category": {},
      "app_testing_url": "test.url",
      "app_title": {
        "en": "action game"
      },
      "app_version": "",
      "app_version_code": null,
      "comments": [
        {
          "comment_text": "unp",
          "commented_at": {
            "$date": 1641530566026
          },
          "commented_by": "nitin.jayant@bluestacks.com",
          "from_state": "marked_for_unpublishing",
          "to_state": "unpublished"
        },
        {
          "comment_text": "un",
          "commented_at": {
            "$date": 1641530558079
          },
          "commented_by": "nitin.jayant@bluestacks.com",
          "from_state": "published",
          "to_state": "marked_for_unpublishing"
        },
        {
          "comment_text": "comment",
          "commented_at": {
            "$date": 1641272004541
          },
          "commented_by": "nitin.jayant@bluestacks.com",
          "from_state": "ready_for_publishing",
          "to_state": "published"
        },
        {
          "comment_text": "post",
          "commented_at": {
            "$date": 1641271987414
          },
          "commented_by": "nitin.jayant@bluestacks.com",
          "from_state": "under_testing",
          "to_state": "ready_for_publishing"
        },
        {
          "comment_text": "testing",
          "commented_at": {
            "$date": 1641271949266
          },
          "commented_by": "nitin.jayant@bluestacks.com",
          "from_state": "submitted",
          "to_state": "under_testing"
        }
      ],
      "created_at": 1641199709347,
      "created_by": "nitin.jayant@bluestacks.com",
      "custom_domain_url": "custom",
      "dev_apk_link": "",
      "id": "61d2b85d2b8108a55d00b768",
      "last_updated_by": "nitin.jayant@bluestacks.com",
      "live_apk_url": "",
      "modified_at": 1641530566026,
      "submission_state": "unpublished",
      "submission_type": "full",
      "uploaded_apk_url": ""
    }
  ];
  return (
    <JsonDiff
      leftCaption="Old Data"
      leftData={data[1]}
      rightCaption="New Data"
      rightData={data[2]}
    />
  );
}
